### ISSUE TITLE
difference between the WHERE and HAVING clause

### ISSUE THREAD

**Issue by karenkathryn** [learn-co-curriculum/dsc-grouping-data-with-sql-lab#3]
After finishing this lab, I still don't understand the difference between the WHERE and HAVING clause. Can this lab have another example?

**Comment by hoffm386** [comment]
The latest version has been updated to include a hint reminder about `WHERE` vs. `HAVING`, and includes some extra exercises highlighting the purpose of `HAVING`. Thanks @karenkathryn, closing this out!
